Правда или действие (часть 1)
htmlacademy-javascript/1446019-keksobooking-25 pull request #6
Opened 2022-03-20 18:36 UTC by snap9595

2022-03-20 20:15 UTC, sahaviev commented on js/form.js
> +const departureTime = form.querySelector('[name="timeout"]');
Вместо departure обычно говорят **checkOut**

2022-03-20 20:19 UTC, sahaviev commented on js/form.js
> +});
Почти, почти получилось то что нужно было сделать)
Правильно так:
```
departureTime.addEventListener('change', (evt) => {
  checkInTime.value = evt.target.value;
});
При изменении селекта времени отъезда(departureTime) тебе нужно установить значение такое же у времени времени заезда.
Не забудь ту же самую логику написать для селекта **checkInTime**
```

2022-03-20 20:19 UTC, sahaviev commented on js/form.js
> +}); */
Это удаляй.

2022-03-20 20:22 UTC, sahaviev requested changes
Нужно доделать комментарии оставил

2022-03-21 06:00 UTC, snap9595 commented on js/form.js
> +});
Оказывается чуть чуть не дошел, и еще пытался реализовать через цикл *рукалицо*

2022-03-21 06:01 UTC, snap9595 commented on js/form.js
> +}); */
Так оставил потому что не получилось и надо было сделать к следующий "домашки"

2022-03-21 16:46 UTC, merged